site_name: Rust中文文档
site_url: https://webtech.wiki/rust
repo_url: https://github.com/webtechwiki/rust
repo_name: Rust Chinese Wiki
site_author: phyxyz

# Copyright
copyright: Copyright &copy; 2022 - 2023 phy.xyz

# Theme
theme:
  name: material
  language: zh
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

# extra
extra:
  alternate:
    - name: 中文
      link: /
      lang: zh-CN

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
# Page tree
nav:
  - 第 0 章 &nbsp; 前言:
    - 0.1 &nbsp; Rust简介: 00_preface/01_introduction.md
  - 第 1 章 &nbsp; 入门指南:
    - 1.1 &nbsp; 安装: 01_primer/01_installation.md
    - 1.2 &nbsp; 运行Hello World: 01_primer/02_hello_world.md
    - 1.3 &nbsp; Cargo构建工具: 01_primer/03_cargo.md
  - 第 2 章 &nbsp; 猜数游戏:
    - 2.1 &nbsp; 猜数游戏: 02_guessing_game/01_guessing_game.md
  - 第 3 章 &nbsp; 通用编程概念:
    - 3.1 &nbsp; 变量与可变性: 03_common_programming_concepts/01_variables.md
    - 3.2 &nbsp; 数据类型: 03_common_programming_concepts/02_data_type.md
    - 3.3 &nbsp; 函数: 03_common_programming_concepts/03_function.md 
    - 3.4 &nbsp; 控制流: 03_common_programming_concepts/04_control_flow.md
  - 第 4 章 &nbsp; 所有权:
    - 4.1 &nbsp; 栈内存和堆内存: 04_ownership/01_stack_and_heap.md
    - 4.2 &nbsp; 所有权规则: 04_ownership/02_ownership_rules.md
    - 4.3 &nbsp; 所有权与函数: 04_ownership/03_ownership_and_function.md
    - 4.4 &nbsp; 引用与借用: 04_ownership/04_reference_and_borrow.md
    - 4.5 &nbsp; 切片: 04_ownership/05_slice.md
  - 第 5 章 &nbsp; 使用结构体组织数据:
    - 5.1 &nbsp; 结构体: 05_struct/01_struct.md
    - 5.2 &nbsp; 结构体示例: 05_struct/02_struct_sample.md
    - 5.3 &nbsp; 结构体方法: 05_struct/03_struct_method.md
  - 第 6 章 &nbsp; 枚举与模式匹配:
    - 6.1 &nbsp; 枚举: 06_enum/01_enum.md
    - 6.2 &nbsp; Option枚举: 06_enum/02_option_enum.md
    - 6.3 &nbsp; math表达式: 06_enum/03_match_expression.md
